### ISSUE TITLE
Stock motor compatibility?

### ISSUE THREAD

**Issue by peterberetich** [LCobeaga/Nerf-Ultra-2-upgrades#2]
Hi!

This is some fantastic work, I am extremely impressed. I was wondering if the V1 versions of the flywheel cages are compatible with stock motors?

Thank you and I apologize if this is the wrong place to ask this.

**Comment by LCobeaga** [comment]
Sadly no. While the V1 appears more like the original cage, it isn't the same geometry, and in the end, the cover piece was redundant. I think blaster tech might sell a version that uses the stock components, but feel free to download the Autodesk Fusion 360 file and make some changes to the mounting and hole diameter there! The V2 is a lot simpler, so I think you would only need to change a few dimensions in there.
