### ISSUE TITLE
How to chose the flywheel cages ?

### ISSUE THREAD

**Issue by Saint-Turgod** [LCobeaga/Nerf-Ultra-2-upgrades#3]
Hello,

First thing first, thanks a lot for sharing those files. This Nerf Ultra 2 converstion mod and all the accessories (grip filler, rev trigger) are a blessing.

This mod is the first one I do on a flywheel blaster, and I am quite confused on how to select the flywheel cage among all of the one you offer.

What is the difference between the 41.5mm cage and the 43mm one ?
Does this refers to the width of the cages ? Or maybe to the space between the motors ?

Could you help me with this please ?
If for instance I would like to use a Fang ReVAMPed 130 2s Neo Motor, do you know wich cage I could use. Or what cage and motor did you used in you own build ?

Best regards,

Saint-Turgod

PS: In advance sorry about my poor english

**Comment by LCobeaga** [comment]
Hello, 

The measurement in the name of each cage is the distance between both motor centers, and a lower distance leads to higher FPS. The cages work with all flywheels, so use something like this site, https://suild.com/tools/flywheel-setup-picker , to check what flywheels and distance you should use for your desired performance.

**Comment by denipo** [comment]
Want to add to the thread - also start with the words of appreciation of work! This is an awesome job mate thank you so much for this!
This is my first mode for the flywheel blaster, and I do not have any other parts than the 3d printed and stock parts that will come from the blaster. 
The question I have: 
When I measured stock motors, they are cylindrical and are about 24mm in diameter. I have printed out the largest cage(43mm) and the placeholder for the motor is still too small.. Could I please ask for help with which cage that should be used for the stock flywheels and stock motor? 
Best regards 
Dennis

**Comment by LCobeaga** [comment]
The dimension that defines each motor is the gap between the center of each motor. There is no cage that fits the stock motors in this file set, nor flywheels. It is meant to be used with aftermarket replacement flywheels and motors. I think someone designed a cage for the stock motors that you can purchase if you want to keep with the stock electronics.
